name: Draft PDF

on:
  push:
    paths:
      - paper.md
      - paper.bib
      - .github/workflows/draft-pdf.yml

  workflow_dispatch:

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build JOSS draft PDF
        uses: openjournals/openjournals-draft-action@v1.0
        with:
          journal: joss
          paper-path: paper.md

      - name: Upload paper.pdf artifact
        uses: actions/upload-artifact@v4
        with:
          name: joss-draft
          path: paper.pdf
          if-no-files-found: error
